# Generated by Django 2.2.8 on 2020-03-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenomeTags',
            fields=[
                ('tagid', models.IntegerField(db_column='tagId', primary_key=True, serialize=False)),
                ('tag', models.TextField()),
            ],
            options={
                'db_table': 'genome-tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('movieid', models.IntegerField(db_column='movieId', primary_key=True, serialize=False)),
                ('imdbid', models.CharField(db_column='imdbId', max_length=50)),
                ('tmdbid', models.CharField(db_column='tmdbId', max_length=50)),
            ],
            options={
                'db_table': 'links',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movieid', models.IntegerField(db_column='movieId', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('genres', models.TextField(blank=True, null=True)),
                ('tmdb', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('adult', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userId')),
                ('movieid', models.IntegerField(db_column='movieId')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.IntegerField(db_column='movieId')),
                ('tag', models.TextField(blank=True, null=True)),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=45)),
                ('userpass', models.CharField(db_column='userPass', max_length=45)),
                ('userhistory', models.TextField(blank=True, db_column='userHistory', null=True)),
                ('usertags', models.TextField(blank=True, db_column='userTags', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
